elib/urls.py
from django.urls import path
from elib import views
from django.contrib import admin

urlpatterns = [
    path('', views.HomeElibView.as_view(), name='elib_index'),
    path('book/<int:book_id>/', views.BookDetail.as_view(), name='book_detail_by_id'),
    path('book/<slug:book_slug>/', views.BookDetail.as_view(), name='book_detail_by_slug'),
    path('books/<slug:genre_slug>/', views.BooksGenre.as_view(), name='books_by_genre'),
    path('books/', views.BooksList.as_view(), name='book_search'),
    path('add_book/', views.AddBook.as_view(), name='add_book'),
]

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Мероприятия библиотеки"

mikorudo/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mikorudo import views, settings

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('admin/', admin.site.urls, name = 'admin'),
    path('elib/', include('elib.urls')),
    path('activities/', include('activities.urls')),
    path('users/', include('users.urls', namespace='users'), )
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = views.bad_request
handler403 = views.forbidden
handler404 = views.page_not_found
handler500 = views.internal_server_error

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),

    path('password-reset/',
         PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

templates/about.html
{% extends 'base.html' %}
{% block content %} 
<a>На этом сайте вы можете познакомиться с электронными книгами или узнать о новых мероприятиях</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>{{title}}</title>
  {% load static %}
  <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
  <div class="gradient-background">
    <div class="content-background">
      {% include 'menu.html' %}
      {% block breadcrumbs %}
	  {% endblock %}
      {% block content %}
      {% endblock %}
      {% block navigation %}
      {% endblock %}
    </div>
  </div>
</body>
</html>

templates/feedback.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h3><a href="https://t.me/mikorudo">Нажмите сюда для связи со мной</a></h3>
<img src="{% static 'imgs/qr.png' %}" alt="QR-код" width="400">
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<a>Добро пожаловать на сайт библиотеки mikorudo!</a>
{% endblock %}

templates/menu.html
<nav role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />

    <span></span>
    <span></span>
    <span></span>

    <ul id="menu">
      {% for m in menu %}
        <a href="{% url m.url_name %}"><li>{{ m.title }}</li></a>
      {% endfor %}
      {% if user.is_authenticated %}
        <a href="{% url 'users:profile' %}"><li>{{user.username}}</li></a>
        <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            <li>Выйти</li>
        </a>
        <form id="logout-form" method="post" action="{% url 'users:logout' %}" style="display: none;">
            {% csrf_token %}
        </form>
      {% else %}
        <a href="{% url 'users:login' %}"><li>Войти</li></a>
        <a href="{% url 'users:register' %}"><li>Регистрация</li></a>
      {% endif %}
    </ul>
  </div>
</nav>